name: Build and Deploy
on:
  push:
    branches:
      - main
env:
  OCTOPUS_URL: 'https://cic.octopus.app'
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
  OCTOPUS_SPACE: Default
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-dotnet-artifacts
          path: ./publish
      - name: Create ZIP package
        run: |
          cd ./publish
          zip -r WebSiteTestPublishPack1.0.1.zip .
          mv WebSiteTestPublishPack1.0.1.zip ../WebSiteTestPublishPack1.0.1.zip
      - name: Install Octopus CLI ğŸ™
        uses: OctopusDeploy/install-octopus-cli-action@v3
        with:
          version: "*"
      - name: Push build information to Octopus Deploy ğŸ™
        uses: OctopusDeploy/push-build-information-action@v3
        with:
          packages: |
            'my-dotnet-artifacts'
          version: 1.0.1
      - name: Push a package to Octopus Deploy ğŸ™
        uses: OctopusDeploy/push-package-action@v3
        with:
          packages: WebSiteTestPublishPack1.0.1.zip
          overwrite_mode: OverwriteExisting
      - name: Create a release in Octopus Deploy ğŸ™
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'CICProject'
          release_number: '1.1.0'
      - name: Deploy a release in Octopus Deploy ğŸ™
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          project: 'CICProject'
          release_number: '1.1.0'
          environments: 'QA'
